[project]
name = "routeros-sim"
version = "1.0.0"
description = "RouterOS Packet Flow Simulator"
requires-python = ">=3.9"
dependencies = ["flet"]

[tool.flet]
org = "com.flaza"
product = "RouterOS Sim"
company = "Flaza"
template = "custom_template"

[tool.flet.app]
path = "src"

[tool.flet.android]
bundle_id = "com.flaza.routerossim"

[tool.flet.flutter.dependencies]
jni = "^1.1.0"
